//! Query planner for optimized filter execution using EventIndex.
//!
//! This module provides a query planner that analyzes filter expressions
//! and generates execution plans that leverage the EventIndex for faster
//! filtering of large event sets (100k+ events).

use prb_core::TransportKind;
use prb_query::ast::{CmpOp, Expr, FieldPath, Value};
use prb_query::{Filter, QueryError};
use std::collections::{HashMap, VecDeque};

const FILTER_CACHE_LIMIT: usize = 100;

/// Query execution plan generated by analyzing a filter expression.
#[derive(Debug, Clone)]
pub enum QueryPlan {
    /// Use the transport (protocol) index to narrow the search space.
    IndexedByTransport {
        /// The transport kind to filter by
        kind: TransportKind,
        /// Remaining filter expression to apply on indexed results
        remaining: Option<Box<Expr>>,
    },

    /// Use the source address index to narrow the search space.
    IndexedBySrc {
        /// The source address to filter by
        addr: String,
        /// Remaining filter expression to apply on indexed results
        remaining: Option<Box<Expr>>,
    },

    /// Use the destination address index to narrow the search space.
    IndexedByDst {
        /// The destination address to filter by
        addr: String,
        /// Remaining filter expression to apply on indexed results
        remaining: Option<Box<Expr>>,
    },

    /// Full scan required - no suitable index found or filter too complex.
    FullScan(Expr),
}

/// Query planner with LRU caching for parsed filters.
pub struct QueryPlanner {
    /// Cache of parsed filter expressions with LRU tracking
    filter_cache: HashMap<String, Filter>,
    filter_lru: VecDeque<String>,
}

impl Default for QueryPlanner {
    fn default() -> Self {
        Self::new()
    }
}

impl QueryPlanner {
    /// Create a new query planner with empty caches.
    pub fn new() -> Self {
        Self {
            filter_cache: HashMap::new(),
            filter_lru: VecDeque::new(),
        }
    }

    /// Parse a filter string and cache the result.
    ///
    /// Uses LRU eviction when cache exceeds FILTER_CACHE_LIMIT entries.
    pub fn parse_filter(&mut self, filter_str: &str) -> Result<Filter, QueryError> {
        // Check if already in cache
        if let Some(filter) = self.filter_cache.get(filter_str) {
            // Update LRU order (move to back)
            self.filter_lru.retain(|s| s != filter_str);
            self.filter_lru.push_back(filter_str.to_string());
            return Ok(filter.clone());
        }

        // Parse the filter
        let filter = Filter::parse(filter_str)?;

        // Add to cache with LRU tracking
        self.filter_cache
            .insert(filter_str.to_string(), filter.clone());
        self.filter_lru.push_back(filter_str.to_string());

        // Evict oldest if over limit
        if self.filter_cache.len() > FILTER_CACHE_LIMIT
            && let Some(oldest) = self.filter_lru.pop_front()
        {
            self.filter_cache.remove(&oldest);
        }

        Ok(filter)
    }

    /// Generate an execution plan for a filter expression.
    ///
    /// Analyzes the AST to identify indexable predicates and generate
    /// an optimized execution plan.
    pub fn plan(&self, expr: &Expr) -> QueryPlan {
        // Try to extract an indexable predicate
        match self.extract_indexable_predicate(expr) {
            Some((plan, remaining)) => {
                // Return plan with remaining filter if needed
                match plan {
                    QueryPlan::IndexedByTransport { kind, .. } => QueryPlan::IndexedByTransport {
                        kind,
                        remaining: remaining.map(Box::new),
                    },
                    QueryPlan::IndexedBySrc { addr, .. } => QueryPlan::IndexedBySrc {
                        addr,
                        remaining: remaining.map(Box::new),
                    },
                    QueryPlan::IndexedByDst { addr, .. } => QueryPlan::IndexedByDst {
                        addr,
                        remaining: remaining.map(Box::new),
                    },
                    QueryPlan::FullScan(e) => QueryPlan::FullScan(e),
                }
            }
            None => {
                // No indexable predicate found, fall back to full scan
                QueryPlan::FullScan(expr.clone())
            }
        }
    }

    /// Extract an indexable predicate from an expression.
    ///
    /// Returns (plan, remaining_filter) if an indexable predicate is found.
    fn extract_indexable_predicate(&self, expr: &Expr) -> Option<(QueryPlan, Option<Expr>)> {
        match expr {
            // Simple comparison - check if it's indexable
            Expr::Compare { field, op, value } => {
                if *op == CmpOp::Eq
                    && let Some(plan) = self.make_index_plan(field, value)
                {
                    return Some((plan, None));
                }
                None
            }

            // AND expression - try to extract indexable predicate from either side
            Expr::And(left, right) => {
                // Try left side first
                if let Expr::Compare { field, op, value } = left.as_ref()
                    && *op == CmpOp::Eq
                    && let Some(plan) = self.make_index_plan(field, value)
                {
                    return Some((plan, Some(right.as_ref().clone())));
                }

                // Try right side
                if let Expr::Compare { field, op, value } = right.as_ref()
                    && *op == CmpOp::Eq
                    && let Some(plan) = self.make_index_plan(field, value)
                {
                    return Some((plan, Some(left.as_ref().clone())));
                }

                // Recursively check left side for nested ANDs
                if let Some((plan, remaining)) = self.extract_indexable_predicate(left) {
                    let combined_remaining = match remaining {
                        Some(rem) => Some(Expr::And(Box::new(rem), right.clone())),
                        None => Some(right.as_ref().clone()),
                    };
                    return Some((plan, combined_remaining));
                }

                // Recursively check right side for nested ANDs
                if let Some((plan, remaining)) = self.extract_indexable_predicate(right) {
                    let combined_remaining = match remaining {
                        Some(rem) => Some(Expr::And(left.clone(), Box::new(rem))),
                        None => Some(left.as_ref().clone()),
                    };
                    return Some((plan, combined_remaining));
                }

                None
            }

            // Other expressions cannot be indexed
            _ => None,
        }
    }

    /// Try to create an index plan for a specific field and value.
    fn make_index_plan(&self, field: &FieldPath, value: &Value) -> Option<QueryPlan> {
        let field_name = field.dotted();

        match field_name.as_str() {
            "transport" => {
                if let Value::String(kind_str) = value {
                    // Try to parse as TransportKind
                    if let Ok(kind) = kind_str.parse::<TransportKind>() {
                        return Some(QueryPlan::IndexedByTransport {
                            kind,
                            remaining: None,
                        });
                    }
                }
                None
            }
            "source.src" | "src" => {
                if let Value::String(addr) = value {
                    return Some(QueryPlan::IndexedBySrc {
                        addr: addr.clone(),
                        remaining: None,
                    });
                }
                None
            }
            "source.dst" | "dst" => {
                if let Value::String(addr) = value {
                    return Some(QueryPlan::IndexedByDst {
                        addr: addr.clone(),
                        remaining: None,
                    });
                }
                None
            }
            _ => None,
        }
    }

    /// Get cache statistics for monitoring.
    pub fn cache_stats(&self) -> CacheStats {
        CacheStats {
            filter_cache_size: self.filter_cache.len(),
        }
    }
}

/// Statistics about the query planner's caches.
#[derive(Debug, Clone, Copy)]
pub struct CacheStats {
    /// Number of entries in the filter cache
    pub filter_cache_size: usize,
}

#[cfg(test)]
mod tests {
    use super::*;
    use prb_query::ast::{Expr, FieldPath, Value};

    #[test]
    fn test_parse_filter_caching() {
        let mut planner = QueryPlanner::new();

        // Parse filter first time
        let filter1 = planner
            .parse_filter(r#"transport == "gRPC""#)
            .expect("parse failed");

        // Parse same filter again - should hit cache
        let filter2 = planner
            .parse_filter(r#"transport == "gRPC""#)
            .expect("parse failed");

        assert_eq!(filter1.source(), filter2.source());
        assert_eq!(planner.filter_cache.len(), 1);
    }

    #[test]
    fn test_filter_cache_lru_eviction() {
        let mut planner = QueryPlanner::new();

        // Fill cache beyond limit
        for i in 0..FILTER_CACHE_LIMIT + 10 {
            let filter_str = format!(r#"id == {}"#, i);
            planner.parse_filter(&filter_str).expect("parse failed");
        }

        // Cache should be at limit
        assert_eq!(planner.filter_cache.len(), FILTER_CACHE_LIMIT);

        // Oldest entries should have been evicted
        assert!(!planner.filter_cache.contains_key("id == 0"));
        assert!(!planner.filter_cache.contains_key("id == 9"));

        // Recent entries should still be present
        let recent_key = format!("id == {}", FILTER_CACHE_LIMIT + 9);
        assert!(planner.filter_cache.contains_key(&recent_key));
    }

    #[test]
    fn test_plan_simple_transport() {
        let planner = QueryPlanner::new();
        let expr = Expr::Compare {
            field: FieldPath(vec!["transport".to_string()]),
            op: CmpOp::Eq,
            value: Value::String("gRPC".to_string()),
        };

        let plan = planner.plan(&expr);
        match plan {
            QueryPlan::IndexedByTransport { kind, remaining } => {
                assert_eq!(kind, TransportKind::Grpc);
                assert!(remaining.is_none());
            }
            _ => panic!("Expected IndexedByTransport plan"),
        }
    }

    #[test]
    fn test_plan_transport_with_and() {
        let planner = QueryPlanner::new();
        let expr = Expr::And(
            Box::new(Expr::Compare {
                field: FieldPath(vec!["transport".to_string()]),
                op: CmpOp::Eq,
                value: Value::String("gRPC".to_string()),
            }),
            Box::new(Expr::Compare {
                field: FieldPath(vec!["id".to_string()]),
                op: CmpOp::Eq,
                value: Value::Number(42.0),
            }),
        );

        let plan = planner.plan(&expr);
        match plan {
            QueryPlan::IndexedByTransport { kind, remaining } => {
                assert_eq!(kind, TransportKind::Grpc);
                assert!(remaining.is_some());
            }
            _ => panic!("Expected IndexedByTransport plan with remaining filter"),
        }
    }

    #[test]
    fn test_plan_src_address() {
        let planner = QueryPlanner::new();
        let expr = Expr::Compare {
            field: FieldPath(vec!["src".to_string()]),
            op: CmpOp::Eq,
            value: Value::String("10.0.0.1:1234".to_string()),
        };

        let plan = planner.plan(&expr);
        match plan {
            QueryPlan::IndexedBySrc { addr, remaining } => {
                assert_eq!(addr, "10.0.0.1:1234");
                assert!(remaining.is_none());
            }
            _ => panic!("Expected IndexedBySrc plan"),
        }
    }

    #[test]
    fn test_plan_dst_address() {
        let planner = QueryPlanner::new();
        let expr = Expr::Compare {
            field: FieldPath(vec!["dst".to_string()]),
            op: CmpOp::Eq,
            value: Value::String("10.0.0.2:5678".to_string()),
        };

        let plan = planner.plan(&expr);
        match plan {
            QueryPlan::IndexedByDst { addr, remaining } => {
                assert_eq!(addr, "10.0.0.2:5678");
                assert!(remaining.is_none());
            }
            _ => panic!("Expected IndexedByDst plan"),
        }
    }

    #[test]
    fn test_plan_complex_or_falls_back_to_full_scan() {
        let planner = QueryPlanner::new();
        let expr = Expr::Or(
            Box::new(Expr::Compare {
                field: FieldPath(vec!["transport".to_string()]),
                op: CmpOp::Eq,
                value: Value::String("gRPC".to_string()),
            }),
            Box::new(Expr::Compare {
                field: FieldPath(vec!["transport".to_string()]),
                op: CmpOp::Eq,
                value: Value::String("ZMQ".to_string()),
            }),
        );

        let plan = planner.plan(&expr);
        match plan {
            QueryPlan::FullScan(_) => {
                // Expected - OR expressions can't be easily indexed
            }
            _ => panic!("Expected FullScan plan for OR expression"),
        }
    }

    #[test]
    fn test_plan_non_equality_falls_back_to_full_scan() {
        let planner = QueryPlanner::new();
        let expr = Expr::Compare {
            field: FieldPath(vec!["id".to_string()]),
            op: CmpOp::Gt,
            value: Value::Number(100.0),
        };

        let plan = planner.plan(&expr);
        match plan {
            QueryPlan::FullScan(_) => {
                // Expected - non-equality comparisons can't use hash indices
            }
            _ => panic!("Expected FullScan plan for non-equality comparison"),
        }
    }

    #[test]
    fn test_cache_stats() {
        let mut planner = QueryPlanner::new();

        planner
            .parse_filter(r#"transport == "gRPC""#)
            .expect("parse failed");

        let stats = planner.cache_stats();
        assert_eq!(stats.filter_cache_size, 1);
    }
}
